In [62]:
from sklearn.decomposition import PCA,SparsePCA
import numpy as np



In [63]:
import pandas as pd
X=pd.read_excel('data.xlsx')

In [64]:
X

Strategy Name  Win% (Best Rank)  Win% (Average Rank)  \
0         Career_averages          0.656645            -0.562608   
1        Tournament_stats          0.836511            -1.258416   
2                     MA5         -1.323616             1.714271   
3                 Random1          1.767831            -1.714271   
4          TOPSIS_Shannon         -1.323616             0.973932   
5              TOPSIS_AHP         -1.323616             0.076432   
6                 Random2          0.205591            -1.714271   
7   Allrounder_Select_All         -0.068071            -0.973932   
8           Career_points         -1.767831             0.391451   
9        TOPSIS_Synthesis         -1.767831            -0.076432   
10               Fav_Team         -0.495920            -1.714271   
11  Mean_var_optimization         -1.323616            -0.231002   
12                    MA1         -1.767831            -0.562608   
13        Allrounder_pref         -1.767831            -0.562608   

    mean (Average Points)  50% (Average Points)  mean (Average Rank)  \
0                0.433213              0.006893             0.106435   
1               -0.077656             -0.176562            -0.428180   
2                2.177605              1.503339             1.378265   
3               -1.525825             -1.692972            -1.694372   
4                0.793943              1.158797             0.896590   
5                1.542615              2.075620             2.733703   
6               -2.177605             -1.832044            -2.733703   
7               -1.275922             -0.586756            -1.275493   
8                0.738537              0.332361             0.657450   
9                0.997323              1.311629             1.037969   
10              -1.782775             -2.075620            -1.705764   
11               0.052014              0.160651             0.065165   
12              -0.289756              0.017352             0.344309   
13              -0.401222             -0.246579             0.246348   

    50% (Average Rank)  mean (Best Rank)  50% (Best Rank)  
0            -0.177629          1.561653         2.072926  
1            -1.142558          1.463287         1.936035  
2             0.465173         -0.842278        -1.006357  
3            -2.071669          2.949447         2.974271  
4             1.089762         -1.042791        -0.648152  
5             2.787955         -0.703237        -0.430727  
6            -1.318635          2.171923         2.373484  
7            -1.746772          0.974745         1.659991  
8             0.676703         -1.212305        -0.853217  
9             1.233278         -0.968170        -0.598971  
10           -2.787955          1.443096         2.265290  
11           -0.258595         -2.949447        -2.974271  
12           -0.036372         -1.581750        -1.645566  
13           -0.049680         -1.776291        -1.674770

In [65]:
z=X.iloc[:,1:].to_numpy()

In [66]:
z

array([[ 0.65664503, -0.56260816,  0.43321336,  0.00689293,  0.10643451,
        -0.17762883,  1.56165313,  2.0729262 ],
       [ 0.8365106 , -1.25841572, -0.07765612, -0.17656247, -0.42818027,
        -1.14255765,  1.4632873 ,  1.93603482],
       [-1.32361606,  1.71427078,  2.17760508,  1.50333859,  1.37826524,
         0.46517286, -0.84227805, -1.00635723],
       [ 1.76783128, -1.71427078, -1.52582538, -1.69297178, -1.6943722 ,
        -2.0716693 ,  2.94944734,  2.97427081],
       [-1.32361606,  0.97393187,  0.79394299,  1.15879692,  0.89659013,
         1.0897616 , -1.0427907 , -0.64815156],
       [-1.32361606,  0.07643184,  1.54261548,  2.0756204 ,  2.73370278,
         2.78795473, -0.70323668, -0.4307273 ],
       [ 0.20559063, -1.71427078, -2.17760508, -1.83204435, -2.73370278,
        -1.31863506,  2.17192323,  2.37348423],
       [-0.06807081, -0.97393187, -1.27592181, -0.58675581, -1.27549333,
        -1.74677246,  0.97474536,  1.65999082],
       [-1.76783128,  0.39145063

In [67]:
pca = PCA(n_components=2)
X_pca = pca.fit_transform(z)

In [68]:
X

Strategy Name  Win% (Best Rank)  Win% (Average Rank)  \
0         Career_averages          0.656645            -0.562608   
1        Tournament_stats          0.836511            -1.258416   
2                     MA5         -1.323616             1.714271   
3                 Random1          1.767831            -1.714271   
4          TOPSIS_Shannon         -1.323616             0.973932   
5              TOPSIS_AHP         -1.323616             0.076432   
6                 Random2          0.205591            -1.714271   
7   Allrounder_Select_All         -0.068071            -0.973932   
8           Career_points         -1.767831             0.391451   
9        TOPSIS_Synthesis         -1.767831            -0.076432   
10               Fav_Team         -0.495920            -1.714271   
11  Mean_var_optimization         -1.323616            -0.231002   
12                    MA1         -1.767831            -0.562608   
13        Allrounder_pref         -1.767831            -0.562608   

    mean (Average Points)  50% (Average Points)  mean (Average Rank)  \
0                0.433213              0.006893             0.106435   
1               -0.077656             -0.176562            -0.428180   
2                2.177605              1.503339             1.378265   
3               -1.525825             -1.692972            -1.694372   
4                0.793943              1.158797             0.896590   
5                1.542615              2.075620             2.733703   
6               -2.177605             -1.832044            -2.733703   
7               -1.275922             -0.586756            -1.275493   
8                0.738537              0.332361             0.657450   
9                0.997323              1.311629             1.037969   
10              -1.782775             -2.075620            -1.705764   
11               0.052014              0.160651             0.065165   
12              -0.289756              0.017352             0.344309   
13              -0.401222             -0.246579             0.246348   

    50% (Average Rank)  mean (Best Rank)  50% (Best Rank)  
0            -0.177629          1.561653         2.072926  
1            -1.142558          1.463287         1.936035  
2             0.465173         -0.842278        -1.006357  
3            -2.071669          2.949447         2.974271  
4             1.089762         -1.042791        -0.648152  
5             2.787955         -0.703237        -0.430727  
6            -1.318635          2.171923         2.373484  
7            -1.746772          0.974745         1.659991  
8             0.676703         -1.212305        -0.853217  
9             1.233278         -0.968170        -0.598971  
10           -2.787955          1.443096         2.265290  
11           -0.258595         -2.949447        -2.974271  
12           -0.036372         -1.581750        -1.645566  
13           -0.049680         -1.776291        -1.674770

In [69]:
#X["Score"]=pca.score_samples(z)

In [70]:
X_pca

array([[ 1.74567278, -2.16764641],
       [ 2.60377571, -1.2349161 ],
       [-3.55126347, -1.24679608],
       [ 5.81770827, -0.78186604],
       [-2.8152143 , -0.63803181],
       [-4.12801452, -2.53625124],
       [ 5.10631881,  0.62711269],
       [ 2.9523001 ,  0.37489935],
       [-2.4608727 ,  0.25444441],
       [-2.83958188, -0.64584681],
       [ 4.65190608,  1.27771971],
       [-3.1531349 ,  2.87441064],
       [-1.99295352,  1.78738781],
       [-1.93664649,  2.0553799 ]])

In [71]:
L=pd.DataFrame(X_pca)

In [72]:
L.columns=["PC1","PC2"]
X=X.join(L)

In [73]:
pca.explained_variance_ratio_

array([0.7850887 , 0.15547061])

In [74]:
pca.singular_values_

array([13.01786462,  5.79301341])

In [75]:
X.set_index("Strategy Name",inplace=True)
X.to_excel('pca.xlsx')

In [76]:
X

Win% (Best Rank)  Win% (Average Rank)  \
Strategy Name                                                  
Career_averages                0.656645            -0.562608   
Tournament_stats               0.836511            -1.258416   
MA5                           -1.323616             1.714271   
Random1                        1.767831            -1.714271   
TOPSIS_Shannon                -1.323616             0.973932   
TOPSIS_AHP                    -1.323616             0.076432   
Random2                        0.205591            -1.714271   
Allrounder_Select_All         -0.068071            -0.973932   
Career_points                 -1.767831             0.391451   
TOPSIS_Synthesis              -1.767831            -0.076432   
Fav_Team                      -0.495920            -1.714271   
Mean_var_optimization         -1.323616            -0.231002   
MA1                           -1.767831            -0.562608   
Allrounder_pref               -1.767831            -0.562608   

                       mean (Average Points)  50% (Average Points)  \
Strategy Name                                                        
Career_averages                     0.433213              0.006893   
Tournament_stats                   -0.077656             -0.176562   
MA5                                 2.177605              1.503339   
Random1                            -1.525825             -1.692972   
TOPSIS_Shannon                      0.793943              1.158797   
TOPSIS_AHP                          1.542615              2.075620   
Random2                            -2.177605             -1.832044   
Allrounder_Select_All              -1.275922             -0.586756   
Career_points                       0.738537              0.332361   
TOPSIS_Synthesis                    0.997323              1.311629   
Fav_Team                           -1.782775             -2.075620   
Mean_var_optimization               0.052014              0.160651   
MA1                                -0.289756              0.017352   
Allrounder_pref                    -0.401222             -0.246579   

                       mean (Average Rank)  50% (Average Rank)  \
Strategy Name                                                    
Career_averages                   0.106435           -0.177629   
Tournament_stats                 -0.428180           -1.142558   
MA5                               1.378265            0.465173   
Random1                          -1.694372           -2.071669   
TOPSIS_Shannon                    0.896590            1.089762   
TOPSIS_AHP                        2.733703            2.787955   
Random2                          -2.733703           -1.318635   
Allrounder_Select_All            -1.275493           -1.746772   
Career_points                     0.657450            0.676703   
TOPSIS_Synthesis                  1.037969            1.233278   
Fav_Team                         -1.705764           -2.787955   
Mean_var_optimization             0.065165           -0.258595   
MA1                               0.344309           -0.036372   
Allrounder_pref                   0.246348           -0.049680   

                       mean (Best Rank)  50% (Best Rank)       PC1       PC2  
Strategy Name                                                                 
Career_averages                1.561653         2.072926  1.745673 -2.167646  
Tournament_stats               1.463287         1.936035  2.603776 -1.234916  
MA5                           -0.842278        -1.006357 -3.551263 -1.246796  
Random1                        2.949447         2.974271  5.817708 -0.781866  
TOPSIS_Shannon                -1.042791        -0.648152 -2.815214 -0.638032  
TOPSIS_AHP                    -0.703237        -0.430727 -4.128015 -2.536251  
Random2                        2.171923         2.373484  5.106319  0.627113  
Allrounder_Select_All          0.974745         1.659991  2.952300  0.374899  
Career_points                 

In [77]:
pca.components_

array([[ 0.27458427, -0.2406854 , -0.30270447, -0.31165742, -0.36045124,
        -0.35764864,  0.44157481,  0.47443409],
       [-0.25099304, -0.15334839, -0.37412639, -0.33221266, -0.33275804,
        -0.34295538, -0.44897225, -0.48293744]])